version: "3.8"
services:
  nvm-node:
    build: .
    container_name: nvm-node
    depends_on:
      - nvm-db
    networks:
      - nvm
  nvm-db:
    image: centos/mysql-80-centos7
    container_name: nvm-db
    expose:
      - 3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - nvm
networks:
  nvm:
